### ISSUE TITLE
HtmlWindow.OnOpeningURL > REDIRECT

### ISSUE THREAD

**Issue by RobinD42** [wxWidgets/Phoenix#1068]
**Operating system**: any
**wxPython version & source**:  4.0.3
**Python version & source**:      any

**Description of the problem**:

See: https://groups.google.com/d/msg/wxpython-users/wS93sD14GzQ/HBjUR1OMCwAJ

Hello everyone,

in wxPython 3 we used the following code to redirect image links:

```python
def OnOpeningURL(self, htmlUrlType, url):
    if (
        htmlUrlType == HTML_URL_IMAGE and
        (self.basePath is not None) and
        not url.startswith(self.basePath)
    ):
        return self.basePath + "/" + url
    else:
        return HTML_OPEN
```

wxPython 4 now raises

```
TypeError: invalid result from HtmlWindow.OnOpeningURL(), a member of enum 'HtmlOpeningStatus' is expected not 'unicode'
```

From reading the docs OnOpeningURL has a fourth parameter redirect which is a Pointer to String variable that must be filled with an URL. How do i use this? I tried

```python
        redirect = self.basePath + "/" + url
        return HTML_REDIRECT
    else:
        return HTML_OPEN
```

but with no success.

How is the correct way of handling the redirect in wxPython 4?

--
TIA,
Torsten

**Comment by RobinD42** [comment]
Fixed by #1069

**Comment by topic2k** [comment]
I've tested again with 4.0.4, but still no success.

The [migration guide](https://docs.wxpython.org/MigrationGuide.html) for OnOpeningURL says
> In Phoenix this has been changed to a simpler wrapper implementation which requires that both an enum value and a string be returned as a tuple

If i do that, it raises a TypeError
`TypeError: invalid result from HtmlWindow.OnOpeningURL(), a member of enum 'HtmlOpeningStatus' is expected not 'tuple'`


From the documentation for [HtmlWindow.OnOpeningURL](https://docs.wxpython.org/wx.html.HtmlWindow.html#wx.html.HtmlWindow.OnOpeningURL):


> <th class="field-name">Return type:</th><td class="field-body"><p class="first last"><a class="reference internal" href="wx.html.HtmlOpeningStatus.enumeration.html#wx-html-htmlopeningstatus"><span class="std std-ref">  wx.html.HtmlOpeningStatus</span></a></p>
> </td>
> </tr>
> </tbody>
> </table>
> <ul class="simple">
> <li><code class="docutils literal"><span class="pre">wx.html.HTML_OPEN</span></code>: Open the URL.</li>
> <li><code class="docutils literal"><span class="pre">wx.html.HTML_BLOCK</span></code>: Deny access to the URL, <a class="reference internal" href="wx.html.HtmlParser.html#wx.html.HtmlParser.OpenURL" title="wx.html.HtmlParser.OpenURL"><code class="xref py py-meth docutils literal"><span class="pre">wx.html.HtmlParser.OpenURL</span></code></a>   will return <code class="docutils literal"><span class="pre">None</span></code>.</li>
> <li><code class="docutils literal"><span class="pre">wx.html.HTML_REDIRECT</span></code>: Don’t open url, redirect to another URL. <a class="reference internal" href="#wx.html.HtmlWindow.OnOpeningURL" title="wx.html.HtmlWindow.OnOpeningURL"><code class="xref py py-meth docutils literal"><span class="pre">OnOpeningURL</span></code></a>   must fill redirect with the new URL. <a class="reference internal" href="#wx.html.HtmlWindow.OnOpeningURL" title="wx.html.HtmlWindow.OnOpeningURL"><code class="xref py py-meth docutils literal"><span class="pre">OnOpeningURL</span></code></a>   will be called again on returned URL.</li>

Just returning `HTML_REDIRECT` will call OnOpeningURL again with an empty url.

**Comment by topic2k** [comment]
@RobinD42 can you have a look at it again, please.

**Comment by RobinD42** [comment]
Uncommenting this code block in the demo works for me. https://github.com/wxWidgets/Phoenix/blob/wxPy-4.0.x/demo/HtmlWindow.py#L42 With that code enabled, when the `HtmlWindow` sample in the demo is run then the links to the geese images are redirected to the Canadian flag image instead.

Does it fail for you? If not then check if you are doing anything differently in your code. If it does, then ensure you are actually using the 4.0.4 release.

**Comment by topic2k** [comment]
Yes, it's still failing. I'm using release 4.0.4 installed with pip.

My test code:
```python
import sys
import wx
import wx.html

print(sys.version)
print(wx.version())

html1 = u'<html><p><img alt="picture.jpg" class="align-center" src="picture.jpg" /></p></html'
html2 = u'<html><p>redirected</p></html>'


class HtmlWindow(wx.html.HtmlWindow):
    def __init__(
        self,
        parent,
        wxid=-1,
        pos=wx.DefaultPosition,
        size=wx.DefaultSize,
        style=wx.html.HW_DEFAULT_STYLE,
        name="htmlWindow"
    ):
        wx.html.HtmlWindow.__init__(self, parent, wxid, pos, size, style, name)

    def OnOpeningURL(self, htmlUrlType, url, redirect):
        if htmlUrlType == wx.html.HTML_URL_IMAGE:
            return wx.html.HTML_REDIRECT, html2
        return wx.html.HTML_OPEN, ""


if __name__ == '__main__':
    a = wx.App()
    w = wx.Frame(None)

    h = HtmlWindow(w)
    h.SetPage(html1)

    w.Show()
    a.MainLoop()
```

and the result:
```shell
2.7.15 Stackless 3.1b3 060516 (default, Jun 24 2018, 16:09:29) [MSC v.1500 32 bit (Intel)]
4.0.4 msw (phoenix) wxWidgets 3.0.5
TypeError: invalid result from HtmlWindow.OnOpeningURL(), a member of enum 'HtmlOpeningStatus' is expected not 'tuple'
```

```shell
`3.7.2 Stackless 3.7 (v3.7.2-slp:85f19043bf, Jan 20 2019, 13:47:31) [MSC v.1916 64 bit (AMD64)]
4.0.4 msw (phoenix) wxWidgets 3.0.5
TypeError: invalid result from HtmlWindow.OnOpeningURL(), a member of enum 'HtmlOpeningStatus' is expected not 'tuple'
``

**Comment by RobinD42** [comment]
Oops, it looks like we are actually talking about different things. I was looking at the implementation of `OnHTMLOpeningURL` (inherited from `HtmlWindowInterface`) and you're using `OnOpeningURL` (from `HtmlWindow`). TBH I'm not sure why we have both as they're doing basically the same thing.

I'll apply the same fix to `OnOpeningURL` but in the meantime you should be able to use `OnHTMLOpeningURL`

BTW, I realize it's just a simple sample, but just in case, regarding your code above you need to return a URL with the REDIRECT flag, not HTML text. Also, you'll need to do something to prevent recursion as there will be another call to OnOpeningURL (or OnHTMLOpeningURL) for the redirection.

**Comment by RobinD42** [comment]
Closed by #1167
