### ISSUE TITLE
wxPython 4.2.1 build failed with cython 3.0.0 and sip 6.7.10

### ISSUE THREAD

**Issue by Suryavarman** [wxWidgets/Phoenix#2439]
[OS] mageia 8:
[wxPython] 4.2.1:    build from the sources tags: wxPython-4.2.1
[Python] 3.11.4:     self-build with the modules:
```
attrdict3 numpy pillow six appdirs setuptools wheel twine sphinx requests pytest 
pytest-xdist pytest-forked pytest-timeout pathlib2 sip wget cython doc2dash beautifulsoup4 
requests[security]
```

**Could not build wheels for wxPython**:

` wx/svg/_nanosvg.pyx:45:8: 'cython.object' is not a valid cython.* module`

<details>
  <summary>Output error(click to expand)</summary>
```
[938/939] Linking build/waf/3.11/gtk3/_aui.cpython-311-x86_64-linux-gnu.so
[939/939] Compiling build/waf/3.11/gtk3/_aui.cpython-311-x86_64-linux-gnu.so
Waf: Leaving directory `/home/toto/Ma/dependencies/wxPython/build/waf/3.11/gtk3'
'build' finished successfully (4m52.812s)
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_baseu-3.2.so --> /home/toto/Ma/dependencies/wxPython/wx/libwx_baseu-3.2.so
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_aui-3.2.so --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_aui-3.2.so
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_webview-3.2.so --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_webview-3.2.so
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_xrc-3.2.so --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_xrc-3.2.so
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_baseu_xml-3.2.so --> /home/toto/Ma/dependencies/wxPython/wx/libwx_baseu_xml-3.2.so
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_media-3.2.so --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_media-3.2.so
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_propgrid-3.2.so --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_propgrid-3.2.so
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_ribbon-3.2.so --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_ribbon-3.2.so
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_core-3.2.so --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_core-3.2.so
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_adv-3.2.so --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_adv-3.2.so
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_richtext-3.2.so --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_richtext-3.2.so
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_baseu_net-3.2.so --> /home/toto/Ma/dependencies/wxPython/wx/libwx_baseu_net-3.2.so
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_stc-3.2.so --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_stc-3.2.so
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_gl-3.2.so --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_gl-3.2.so
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_html-3.2.so --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_html-3.2.so
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_baseu-3.2.so.0 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_baseu-3.2.so.0
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_aui-3.2.so.0.2.1 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_aui-3.2.so.0.2.1
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_stc-3.2.so.0.2.1 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_stc-3.2.so.0.2.1
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_propgrid-3.2.so.0 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_propgrid-3.2.so.0
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_baseu_net-3.2.so.0 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_baseu_net-3.2.so.0
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_xrc-3.2.so.0.2.1 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_xrc-3.2.so.0.2.1
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_html-3.2.so.0 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_html-3.2.so.0
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_propgrid-3.2.so.0.2.1 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_propgrid-3.2.so.0.2.1
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_ribbon-3.2.so.0 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_ribbon-3.2.so.0
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_webview-3.2.so.0 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_webview-3.2.so.0
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_baseu_net-3.2.so.0.2.1 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_baseu_net-3.2.so.0.2.1
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_webview-3.2.so.0.2.1 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_webview-3.2.so.0.2.1
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_adv-3.2.so.0.2.1 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_adv-3.2.so.0.2.1
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_core-3.2.so.0 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_core-3.2.so.0
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_core-3.2.so.0.2.1 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_core-3.2.so.0.2.1
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_media-3.2.so.0.2.1 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_media-3.2.so.0.2.1
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_richtext-3.2.so.0.2.1 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_richtext-3.2.so.0.2.1
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_html-3.2.so.0.2.1 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_html-3.2.so.0.2.1
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_baseu_xml-3.2.so.0.2.1 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_baseu_xml-3.2.so.0.2.1
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_baseu-3.2.so.0.2.1 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_baseu-3.2.so.0.2.1
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_ribbon-3.2.so.0.2.1 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_ribbon-3.2.so.0.2.1
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_gl-3.2.so.0 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_gl-3.2.so.0
copying /home/toto/Ma/dependencies/wxPython/build/wxbld/gtk3/lib/libwx_gtk3u_gl-3.2.so.0.2.1 --> /home/toto/Ma/dependencies/wxPython/wx/libwx_gtk3u_gl-3.2.so.0.2.1
Running command: build_others
Running command: build_others
          /home/toto/Ma/dependencies/venv/bin/python3.11 setup-wxsvg.py build_ext --inplace
          Compiling wx/svg/_nanosvg.pyx because it changed.
          [1/1] Cythonizing wx/svg/_nanosvg.pyx
          
          Error compiling Cython file:
          ------------------------------------------------------------
          ...
          for manipulating the SVG shape info in memory.
          """
          
          import sys
          
          cimport cython.object
                  ^
          ------------------------------------------------------------
          
          wx/svg/_nanosvg.pyx:45:8: 'cython.object' is not a valid cython.* module
          Traceback (most recent call last):
            File "/home/toto/Ma/dependencies/wxPython/setup-wxsvg.py", line 54, in <module>
              modules = cythonize([module],
                        ^^^^^^^^^^^^^^^^^^^
            File "/home/toto/Ma/dependencies/venv/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
              cythonize_one(*args)
            File "/home/toto/Ma/dependencies/venv/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
              raise CompileError(None, pyx_file)
          Cython.Compiler.Errors.CompileError: wx/svg/_nanosvg.pyx
          Command '/home/toto/Ma/dependencies/venv/bin/python3.11 setup-wxsvg.py build_ext --inplace' failed with exit code 1.
          Finished command: build_others (0.737s)
          Finished command: build_py (4m55.473s)
          Finished command: build (6m30.855s)
          Command '"/home/toto/Ma/dependencies/venv/bin/python3.11" -u build.py build' failed with exit code 1.

note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for wxPython
      Running setup.py clean for wxPython
    Failed to build wxPython
    ERROR: Could not build wheels for wxPython, which is required to install pyproject.toml-based projects
```

</details>

**Comment by swt2c** [comment]
What version of `cython` do you have installed?

**Comment by Suryavarman** [comment]
The last one cython 3.0.0 ( https://github.com/cython/cython/tree/3.0.0 ).
I'll try with the second last one: 0.29.36.

**Comment by Suryavarman** [comment]
With cython 0.29.36, the error in the cython object module disappears. 
Another error appears:
```
          In the file included from ../../../../venv/include/python3.11/Python.h:38,
                           from ../../../sip/siplib/sip.h:24,
                           from ../../../sip/cpp/sipAPI_core.h:13,
                           from ../../../sip/cpp/sip_corecmodule.cpp:10:
          ../../../../sip/cpp/sip_corecmodule.cpp: In the "PyObject* func_LogInfo(PyObject*, PyObject*)" function:
          ../../../../sip/cpp/sip_corecmodule.cpp:15760:23: error: "a1" was not declared in this scope; did you want to use "y1"?
```

**Comment by swt2c** [comment]
Yes, that's a different problem.  You can roll back to sip == 6.7.9 for that problem.

**Comment by swt2c** [comment]
https://github.com/wxWidgets/Phoenix/pull/2441 should fix the first problem.  The second problem seems to be a bug in sip itself, which I've reported.

**Comment by Suryavarman** [comment]
Thank you very much, the problem has been solved. :)

**Comment by swt2c** [comment]
sip 6.7.11 has been released which has fixed the other problem, closing.

**Comment by 2sn** [comment]
wxPython 4.2.1 seems to be still failing with Cython 3.0.0

**Comment by 2sn** [comment]
Unfortunately, install with Cython 3.0.0 still fails from both PyPI and this git repo

```
pip3 install git+https://github.com/wxWidgets/Phoenix.git
```

results in 

```
        File "/home/alex/Python/lib/python3.11/site-packages/setuptools/_distutils/file_util.py", line 115, in copy_file
          raise DistutilsFileError(
      distutils.errors.DistutilsFileError: can't copy 'sip/siplib/LICENSE': doesn't exist or not a regular file
      Command '"/home/alex/Python/bin/python3.11" /tmp/pip-req-build-yvczm2rm/bin/waf-2.0.24 --wx_config=/tmp/pip-req-build-yvczm2rm/build/wxbld/gtk3/wx-config --gtk3 --python="/home/alex/Python/bin/python3.11" --out=build/waf/3.11/gtk3 configure build ' failed with exit code 2.
```

**Comment by swt2c** [comment]
> Unfortunately, install with Cython 3.0.0 still fails from both PyPI and this git repo
> 
> ```
> pip3 install git+https://github.com/wxWidgets/Phoenix.git
> ```
> 
> results in
> 
> ```
>         File "/home/alex/Python/lib/python3.11/site-packages/setuptools/_distutils/file_util.py", line 115, in copy_file
>           raise DistutilsFileError(
>       distutils.errors.DistutilsFileError: can't copy 'sip/siplib/LICENSE': doesn't exist or not a regular file
>       Command '"/home/alex/Python/bin/python3.11" /tmp/pip-req-build-yvczm2rm/bin/waf-2.0.24 --wx_config=/tmp/pip-req-build-yvczm2rm/build/wxbld/gtk3/wx-config --gtk3 --python="/home/alex/Python/bin/python3.11" --out=build/waf/3.11/gtk3 configure build ' failed with exit code 2.
> ```

Building from git like that doesn't work.  You can try using one of the snapshot releases here:
https://wxpython.org/Phoenix/snapshot-builds/

**Comment by 2sn** [comment]
Unfortunately no linux version.

**Comment by 2sn** [comment]
my apologies, this is what I thought 
```
pip3 install git+https://github.com/wxWidgets/Phoenix.git
```
was going to do.

**Comment by swt2c** [comment]
On Mon, 21 Aug 2023, Alexander Heger wrote:

> my apologies, this is what I thought
> 
> pip3 install git+https://github.com/wxWidgets/Phoenix.git
> 
> was going to do.

No, the git repository doesn't contain *all* of the source.

**Comment by 2sn** [comment]
OK, that part I do not understand.  
I assume I will then have to wait for the next release on PyPI.
No worries.

**Comment by JohnPritchard** [comment]
I'm getting this problem again, building in MacPorts, with the following versions:

- wxpython @4.2.1
- sip @6.8.1
- cython @3.0.7

The weird thing is this worked ~3weeks ago (though possibly with different versions of sip and/or cython.

**Comment by JohnPritchard** [comment]
I have created a new ticket https://github.com/wxWidgets/Phoenix/issues/2514 for this issue now since I am unsure if this closed ticket can be reopened.
